export const ErrorMessage = {
  TOKEN_REQUIRED: "Token is required",
  INVALID_TOKEN: "Invalid token",
  SESSION_EXPIRED: "Token expired",
  UNAUTHORIZED: "Unauthorized",
  INTERNAL_SERVER_ERROR: "Internal server error",
  SOMETHING_WENT_WRONG: "Something went wrong!",

  // Auth module
  PASSWORD_REQUIRED: "Password is required",
  NICKNAME_REQUIRED: "Nickname is required",
  IDENTIFIER_NUMBER_REQUIRED: "Identifier number is required",
};

export const ErrorCode = {
  INVALID_TOKEN: "INVALID_TOKEN",
  SESSION_EXPIRED: "SESSION_EXPIRED",
  UNAUTHORIZED: "UNAUTHORIZED",
  INTERNAL_SERVER_ERROR: "INTERNAL_SERVER_ERROR",
  FORBIDDEN: "FORBIDDEN",
  NOT_FOUND: "NOT_FOUND",
  CONFLICT: "CONFLICT",
  DOMAIN_ERROR: "DOMAIN_ERROR",
  TOO_MANY_REQUESTS: "TOO_MANY_REQUESTS",
  SERVICE_UNAVAILABLE: "SERVICE_UNAVAILABLE",
  SOMETHING_WENT_WRONG: "SOMETHING_WENT_WRONG",
  BAD_REQUEST: "BAD_REQUEST",
};

export const StatusCode = {
  OK: 200,
  CREATED: 201,
  BAD_REQUEST: 400,
  UNAUTHORIZED: 401,
  FORBIDDEN: 403,
  NOT_FOUND: 404,
  CONFLICT: 409,
  DOMAIN_ERROR: 422,
  TOO_MANY_REQUESTS: 429,
  INTERNAL_SERVER_ERROR: 500,
  SERVICE_UNAVAILABLE: 503,
};
